### ISSUE TITLE
Feeder wifi connection setup

### ISSUE THREAD

**Issue by jupmoreno** [petnet-independence-project/petnet-feeder-service#41]
Hi, I’m considering buying a used V2 Feeder and would like to know if I can use this service with it. 

After reading the readme I believe that the wifi connection cannot be changed. Is this right? Can this be done in any way? Just wanna make sure before buying it and not being able to use it.

Thanks!

**Comment by kruton** [comment]
The other project in this organization is an Android application that can set the WiFi credentials. It's a bit rough, but it works.

https://github.com/petnet-independence-project/petnet-android

**Comment by mbillow** [comment]
I am also idly hacking together an iOS app that does the same. I have never written Swift or developed for iOS before though, so it is being developed at the speed of the Xcode learning curve. 

Also, a note: we haven't fully finished the scheduling features yet. So you will be able to connect your feeder, manually dispense food via the app, change settings, etc. You just won't be able to set a schedule. I have the UI and API written for it ([branch](https://github.com/mbillow/petnet-feeder-service/tree/pets-and-scheduling)), we just need to hammer out the Service<->Feeder comms for scheduling.

**Comment by jupmoreno** [comment]
Thank you both for your replies!

> Also, a note: we haven't fully finished the scheduling features yet. So you will be able to connect your feeder, manually dispense food via the app, change settings, etc. You just won't be able to set a schedule. I have the UI and API written for it (branch), we just need to hammer out the Service<->Feeder comms for scheduling.

The scheduling feature is not available in the web interface either or is it a limitation of the mobile clients only?

**Comment by mbillow** [comment]
The mobile apps are only for reconfiguring or initially setting the WiFi credentials. After the feeder is online, everything is done via the web interface.

**Comment by mbillow** [comment]
I am going to close this out since I think all your questions are answered. Feel free to make a new issue if you run into any issues! 😄

**Comment by tedder** [comment]
@jupmoreno - you should join us in Slack.
